apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::582553792189:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::582553792189:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UVJ9WT1BOM3P
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-04T00:23:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1330"
  uid: 401bca30-687f-43ee-93da-a8db4d0ac43d
